---
settings:
  name: StorageGRID solutions and resources
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: true
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: StorageGRID Lösungen und Ressourcen
    url: "/index.html"
  - title: StorageGRID testen
    url: "/evaluation-software.html"
  - section: third-party
  - section: product-feature-guides
  - section: tools-apps-guides
  - section: examples
  - section: technical-reports
  - title: StorageGRID testen
    url: "/evaluation-software.html"
  - title: Blogbeiträge
    url: "/blogs.html"
  - title: StorageGRID-Dokumentation
    url: "/storagegrid-documentation.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
