---
sidebar: sidebar 
permalink: technical-reports/bare-metal-index.html 
keywords: install, storagegrid, deploy, bare metal 
summary: Erfahren Sie, wie Sie StorageGRID auf einem Bare-Metal-Grid installieren. 
---
= Einführung in die Installation von StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie Sie StorageGRID auf Bare-Metal-Hosts installieren.

TR-4882 bietet eine praktische Schritt-für-Schritt-Anleitung, die zu einer funktionierenden Installation von NetApp StorageGRID führt. Die Installation kann entweder auf Bare-Metal-Systemen oder auf Virtual Machines (VMs) erfolgen, die unter Red hat Enterprise Linux (RHEL) ausgeführt werden. Der Ansatz besteht darin, eine „opinionierte“ Installation von sechs StorageGRID Container-Services auf drei physischen (oder virtuellen) Maschinen mit einer vorgegebenen Layout- und Storage-Konfiguration durchzuführen. Einige Kunden finden es unter Umständen leichter, den Implementierungsprozess zu verstehen, indem sie dem Beispiel folgen, das in diesem TR bereitgestellt wird.

Weitere Informationen zu StorageGRID und dem Installationsprozess finden Sie unter https://docs.netapp.com/us-en/storagegrid-118/landing-install-upgrade/index.html[] [StorageGRID installieren, aktualisieren und Hotfix] in der Produktdokumentation.

Bevor Sie mit der Bereitstellung beginnen, werden die Rechen-, Speicher- und Netzwerkanforderungen für die NetApp StorageGRID Software betrachtet. StorageGRID läuft als containerisierter Dienst innerhalb von Podman oder Docker. In diesem Modell beziehen sich einige Anforderungen auf das Host-Betriebssystem (das Betriebssystem, das Docker hostet, welches die StorageGRID Software ausführt). Einige Ressourcen werden direkt den Docker Containern zugewiesen, die auf jedem Host ausgeführt werden. In dieser Bereitstellung werden zur Maximierung der Hardwareauslastung zwei Dienste pro physischem Host bereitgestellt. Weitere Informationen enthält der nächste Abschnitt link:bare-metal-prerequisites-install-storagegrid.html["Voraussetzungen für die Installation von StorageGRID"].

Die in dieser TR beschriebenen Schritte führen zu einer funktionierenden StorageGRID-Installation auf sechs Bare-Metal-Hosts. Sie verfügen jetzt über ein funktionierendes Grid- und Client-Netzwerk, das in den meisten Testszenarien nützlich ist.



[[where-to-find-additional-information]]
== Wo Sie weitere Informationen finden

Folgende Dokumentationsressourcen enthalten weitere Informationen zu den in diesem TR enthaltenen Informationen:

* NetApp StorageGRID Dokumentationszentrum https://docs.netapp.com/us-en/storagegrid-118/[]
* NetApp StorageGRID Enablement https://docs.netapp.com/us-en/storagegrid-enable/[]
* NetApp Produktdokumentation https://www.netapp.com/support-and-training/documentation/[]

