---
sidebar: sidebar 
permalink: technical-reports/commvault-index.html 
keywords: Backup, on-premises, commvault, storagegrid, object, S3, WORM 
summary: Sehen Sie sich einige Anwendungsfälle für StorageGRID-Konfigurationen an, die von Kunden und NetApp IT implementiert wurden. 
---
= Backup und Recovery von Daten mit StorageGRID und CommVault
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
CommVault und NetApp haben gemeinsam eine gemeinsame Datensicherungslösung entwickelt, die CommVault Complete Backup and Recovery for NetApp Software mit der NetApp StorageGRID Software für Cloud-Storage kombiniert. CommVault Complete Backup and Recovery und NetApp StorageGRID bieten einzigartige, benutzerfreundliche Lösungen, die Sie dabei unterstützen, die Anforderungen eines schnellen Datenwachstums und die zunehmenden Vorschriften weltweit zu erfüllen.

Viele Unternehmen möchten ihren Storage in die Cloud migrieren, ihre Systeme skalieren und ihre Richtlinien zur langfristigen Aufbewahrung von Daten automatisieren. Cloud-basierter Objekt-Storage ist für seine Ausfallsicherheit, Skalierbarkeit und betriebliche und Kosteneffizienz bekannt, die es zur ersten Wahl für Ihr Backup machen. CommVault und NetApp haben ihre kombinierte Lösung 2014 gemeinsam zertifiziert und bieten seitdem eine engere Integration der beiden Lösungen an. Kunden aller Branchen weltweit haben die kombinierte Lösung CommVault Complete Backup and Recovery sowie StorageGRID eingeführt.



== CommVault und StorageGRID

Die Software CommVault Complete Backup and Recovery ist eine integrierte Daten- und Informationsmanagement-Lösung der Enterprise-Klasse, die von Grund auf auf auf einer einzigen Plattform und mit einer einheitlichen Code-Basis aufgebaut wurde. Alle Funktionen sind mit Back-End-Technologien ausgestattet und bieten so die unvergleichlichen Vorteile und Vorteile eines vollständig integrierten Ansatzes zum Schutz, Management und Zugriff auf Ihre Daten. Die Software enthält Module zum Schützen, Archivieren, Analysieren, Replizieren und Durchsuchen Ihrer Daten. Die Module verfügen über gemeinsame Back-End-Services und erweiterte Funktionen, die nahtlos miteinander interagieren. Die Lösung deckt alle Aspekte des Datenmanagements in Ihrem Unternehmen ab und sorgt gleichzeitig für grenzenlose Skalierbarkeit und beispiellose Kontrolle über Daten und Informationen.

NetApp StorageGRID als Cloud-Tier von CommVault ist eine Objekt-Storage-Lösung für die Hybrid Cloud der Enterprise-Klasse. Sie kann an mehreren Standorten eingesetzt werden, entweder auf einer speziell entwickelten Appliance oder als softwaredefinierte Implementierung. Mit StorageGRID können Kunden Richtlinien für das Datenmanagement festlegen, die festlegen, wie Daten gespeichert und gesichert werden. StorageGRID erfasst die Informationen, die Sie für die Entwicklung und Durchsetzung von Richtlinien benötigen. Untersucht werden eine Vielzahl von Merkmalen und Anforderungen, darunter Performance, Langlebigkeit, Verfügbarkeit, geografischer Standort Langlebigkeit und Kosten. Daten werden während der Verschiebung zwischen Standorten und mit zunehmendem Alter vollständig gepflegt und geschützt.

Die intelligente Richtlinien-Engine von StorageGRID bietet Ihnen eine der folgenden Optionen:

* Mit Erasure Coding können Sie Daten aus Resilience-heraus über mehrere Standorte hinweg sichern.
* Um Objekte an Remote-Standorte zu kopieren und so die WAN-Latenz und die Kosten zu minimieren.


Wenn ein Objekt von StorageGRID gespeichert wird, greifen Sie als ein Objekt auf es zu, unabhängig davon, wo es sich befindet oder wie viele Kopien vorhanden sind. Dieses Verhalten ist bei der Disaster Recovery von entscheidender Bedeutung, da StorageGRID Ihre Daten selbst dann wiederherstellen kann, wenn eine Sicherungskopie der Daten beschädigt ist.

Die Aufbewahrung von Backup-Daten in Ihrem Primärspeicher kann kostspielig werden. Wenn Sie NetApp StorageGRID verwenden, geben Sie Speicherplatz auf Ihrem primären Storage frei, indem Sie inaktive Backup-Daten in StorageGRID migrieren und gleichzeitig von den zahlreichen Funktionen von StorageGRID profitieren. Der Wert von Backup-Daten ändert sich im Laufe der Zeit, genauso wie die Kosten für deren Speicherung. StorageGRID kann die Kosten für primären Storage minimieren und die Langlebigkeit der Daten verbessern.



== Wichtige Funktionen

Zu den wichtigsten Funktionen der CommVault Softwareplattform gehören:

* Eine umfassende Datensicherungslösung, die alle wichtigen Betriebssysteme, Applikationen und Datenbanken auf virtuellen und physischen Servern, NAS-Systemen, Cloud-basierten Infrastrukturen und Mobilgeräten unterstützt
* Vereinfachtes Management über eine einzige Konsole: Sie können alle Funktionen sowie alle Daten und Informationen im gesamten Unternehmen anzeigen, managen und darauf zugreifen.
* Verschiedene Sicherungsmethoden wie Daten-Backup und -Archivierung, Snapshot-Management, Datenreplizierung und Content-Indizierung für E-Discovery
* Effizientes Storage-Management mit Deduplizierung für Festplatten- und Cloud-Storage
* Integration in NetApp Storage-Arrays wie AFF, FAS, NetApp HCI und E-Series Arrays sowie^ horizontal skalierbare NetApp SolidFire^ Storage-Systeme Auch in die NetApp Cloud Volumes ONTAP Software integrierbar, um die Erstellung indizierter, applikationsgerechter NetApp Snapshot™ Kopien im gesamten NetApp Storage-Portfolio zu automatisieren.
* Umfassendes Management virtueller Infrastrukturen, das führende lokale virtuelle Hypervisoren und Hyperscaler-Plattformen für Public Clouds unterstützt
* Erweiterte Sicherheitsfunktionen zur Einschränkung des Zugriffs auf kritische Daten, zur Bereitstellung granularer Verwaltungsfunktionen und zur Bereitstellung von Single-Sign-on-Zugriff für Active Directory-Benutzer.
* Richtlinienbasiertes Datenmanagement, mit dem Daten je nach Geschäftsanforderungen und nicht nach physischem Standort gemanagt werden können
* Eine hochmoderne End-User-Erfahrung, mit der Ihre Anwender ihre Daten selbst schützen, finden und wiederherstellen können.
* API-gestützte Automatisierung, sodass Sie zum Management Ihrer Datensicherungs- und Recovery-Vorgänge Tools von Drittanbietern wie vRealize Automation oder Service Now verwenden können.


Weitere Informationen zu unterstützten Workloads finden Sie unter https://www.commvault.com/supported-technologies["Die unterstützten Technologien von CommVault"].



== Backup-Optionen

Die Implementierung der CommVault Complete Backup and Recovery-Software mit Cloud-Storage bietet zwei Backup-Optionen:

* Es wird ein Backup auf ein primäres Festplattenziel erstellt und außerdem eine zusätzliche Kopie in einem Cloud-Storage gesichert.
* Backup auf Cloud-Storage als primäres Ziel,


In der Vergangenheit wurde Cloud- oder Objekt-Storage als zu leistungsschwach für das primäre Backup angesehen. Durch die Verwendung eines primären Festplattenziels konnten Kunden schnellere Backup- und Restore-Prozesse durchführen und eine zusätzliche Kopie als Cold Backup in der Cloud aufbewahren. StorageGRID ist die Objekt-Storage-Generation der nächsten Generation. StorageGRID bietet neben hoher Performance und enormem Durchsatz auch Performance und Flexibilität eine im Vergleich zu anderen Objekt-Storage-Anbietern hervorragende Leistung.

In der folgenden Tabelle sind die Vorteile der einzelnen Backup-Optionen mit StorageGRID aufgeführt:

[cols="1a,1a,1a"]
|===
|  | Primäres Backup-to-Disk und eine zusätzliche Kopie an StorageGRID | Primäres Backup auf StorageGRID 


 a| 
Leistung
 a| 
Schnellste Recovery-Zeit mithilfe von Live-Mounten oder Live-Recovery: Ideal für Tier 0/Tier 1-Workloads.
 a| 
Kann nicht für Live-Mount- oder Live-Recovery-Vorgänge verwendet werden. Ideal für Streaming-Wiederherstellungsvorgänge und für langfristige Aufbewahrung.



 a| 
Implementierungsarchitektur
 a| 
Verwendet rein Flash-basierten oder rotierenden Festplatten als erste Backup-Landing Tier. StorageGRID wird als sekundäre Ebene verwendet.
 a| 
Vereinfacht die Implementierung durch die Verwendung von StorageGRID als umfassendes Backup-Ziel.



 a| 
Erweiterte Funktionen (Live-Wiederherstellung)
 a| 
Unterstützt
 a| 
Nicht unterstützt

|===


== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* StorageGRID 11.9 Dokumentationszentrum + https://docs.netapp.com/us-en/storagegrid-119/[]
* NetApp Produktdokumentation +
https://docs.netapp.com[]
* CommVault Dokumentation +
https://documentation.commvault.com/2024/essential/index.html[]

