---
sidebar: sidebar 
permalink: technical-reports/data-security-index.html 
keywords: security features, storagegrid 
summary: Entdecken Sie die integrierten Sicherheitsfunktionen der StorageGRID Objekt-Storage-Lösung. 
---
= Sichern von StorageGRID-Daten und -Metadaten in einem Objektspeicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Entdecken Sie die integrierten Sicherheitsfunktionen der StorageGRID Objekt-Storage-Lösung.

Dies ist eine Übersicht über die zahlreichen Sicherheitsfunktionen in NetApp® StorageGRID®, die Datenzugriff, Objekte und Metadaten, Administratorzugriff und Plattformsicherheit abdecken.  Es wurde aktualisiert, um die neuesten Funktionen zu enthalten, die mit StorageGRID 12.0 veröffentlicht wurden.

Sicherheit ist ein integraler Bestandteil der NetApp StorageGRID Objekt-Storage-Lösung. Die Sicherheit ist besonders wichtig, da viele Arten von umfangreichen Datenmengen, die gut für Objekt-Storage geeignet sind, ebenfalls sehr sensibel sind und gesetzlichen Vorschriften und Compliance unterliegen. Während sich die Funktionen von StorageGRID weiterentwickeln, stellt die Software viele Sicherheitsfunktionen zur Verfügung, die von unschätzbarem Wert sind, um die Sicherheit eines Unternehmens zu schützen und dem Unternehmen dabei zu helfen, die Best Practices der Branche einzuhalten.

Dieses Dokument bietet einen Überblick über die zahlreichen Sicherheitsfunktionen in StorageGRID 12.0, unterteilt in fünf Kategorien:

* Sicherheitsfunktionen für den Datenzugriff
* Sicherheitsfunktionen für Objekte und Metadaten
* Sicherheitsfunktionen für die Administration
* Plattformsicherheitsfunktionen
* Cloud-Integration


Dieses Dokument ist als Sicherheitsdatenblatt gedacht. Es enthält keine detaillierten Informationen zur Konfiguration des Systems, um die darin aufgeführten Sicherheitsfunktionen zu unterstützen, die nicht standardmäßig konfiguriert sind.  Der https://docs.netapp.com/us-en/storagegrid/harden/index.html["Leitfaden zum StorageGRID Hardening"^] ist auf der offiziellen https://docs.netapp.com/us-en/storagegrid/["StorageGRID-Dokumentation"^] Seite.

Zusätzlich zu den in diesem Bericht beschriebenen Funktionen folgt StorageGRID den https://www.netapp.com/us/legal/vulnerability-response.aspx["NetApp Richtlinie zur Reaktion auf und Benachrichtigung bei Produktsicherheitsschwachstellen"^]. Gemeldete Schwachstellen werden überprüft und entsprechend dem Reaktionsprozess für Produktsicherheitsvorfälle reagiert.

NetApp StorageGRID bietet erweiterte Sicherheitsfunktionen für äußerst anspruchsvolle Enterprise-Objekt-Storage-Anwendungsfälle.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* NetApp StorageGRID: Bewertung DER Compliance-Anforderungen gemäß SEC 17a-4(f), FINRA 4511(c) und CFTC 1.31(c)-(d) https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* NetApp StorageGRID NIST FIPS 140-3 Kernel Crypto-Zertifizierung https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/5097[]
* NetApp StorageGRID NIST SP 800-90B Entropie-Zertifizierung https://csrc.nist.gov/projects/cryptographic-module-validation-program/entropy-validations/certificate/223[]
* NetApp StorageGRID Canadian Centre for Cyber ​​Security Common Criteria Zertifizierung https://www.commoncriteriaportal.org/nfs/ccpfiles/files/epfiles/565-LSS%20CT%20v1.0.pdf[]
* StorageGRID -Dokumentationsseitehttps://docs.netapp.com/us-en/storagegrid/[]
* NetApp Produktdokumentation https://www.netapp.com/support-and-training/documentation/[]




== Begriffe und Akronyme

Dieser Abschnitt enthält Definitionen für die im Dokument verwendete Terminologie.

[cols="40,60"]
|===
| Begriff oder Akronym | Definition 


| S3 | Simple Storage Service. 


| Client | Eine Applikation, die eine Schnittstelle zu StorageGRID entweder über das S3-Protokoll für den Datenzugriff oder das HTTP-Protokoll für das Management bietet. 


| Mandantenadministrator | Der Administrator des StorageGRID-Mandantenkontos 


| Mandantenbenutzer | Ein Benutzer in einem StorageGRID-Mandantenkonto 


| TLS | Sicherheit In Transportschicht 


| ILM | Information Lifecycle Management 


| LAN | Lokales Netzwerk 


| Grid-Administrator | Der Administrator des StorageGRID-Systems 


| Raster | Dem StorageGRID-System 


| Eimer | Ein Container für in S3 gespeicherte Objekte 


| LDAP | Lightweight Directory Access Protocol 


| SEK. | Securities and Exchange Commission; regelt Börsenmitglieder, Makler oder Händler 


| FINRA | Aufsichtsbehörde für die Finanzindustrie; entspricht den Format- und Medienanforderungen der SEC Rule 17a-4(f) 


| CFTC | Commodities Futures Trading Commissions; regelt den Handel mit Rohstofftermingeschäften 


| NIST | National Institute of Standards and Technology 
|===