---
sidebar: sidebar 
permalink: technical-reports/data-security-platform-security.html 
keywords: platform security, storagegrid 
summary: Erfahren Sie mehr über die Plattformsicherheitsfunktionen in StorageGRID. 
---
= Plattformsicherheitsfunktionen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Plattformsicherheitsfunktionen in StorageGRID.

[cols="20,30a,30,20"]
|===
| Funktion | Funktion | Auswirkungen | Einhaltung gesetzlicher Vorschriften 


| Interne Public-Key-Infrastruktur (PKI), Node-Zertifikate und TLS  a| 
StorageGRID verwendet interne PKI- und Node-Zertifikate zur Authentifizierung und Verschlüsselung der Kommunikation zwischen den Knoten. Die Kommunikation zwischen den Knoten ist durch TLS gesichert.
| Unterstützt den sicheren Systemdatenverkehr über LAN oder WAN, insbesondere bei standortübergreifenden Bereitstellungen. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 


| Knoten-Firewall  a| 
StorageGRID konfiguriert automatisch IP-Tabellen und Firewallregeln zur Steuerung von eingehendem und ausgehendem Netzwerk-Traffic sowie zum Schließen nicht verwendeter Ports.
| Der Schutz von StorageGRID-Systemen, Daten und Metadaten vor unaufgefordertem Netzwerkverkehr | -- 


| OS-Sicherung  a| 
Das Basis-Betriebssystem der physischen Appliances und virtuellen Nodes von StorageGRID ist gehärtet; zugehörige Softwarepakete werden entfernt.
| Minimiert mögliche Angriffsflächen. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 


| Regelmäßige Plattform- und Software-Updates  a| 
StorageGRID veröffentlicht regelmäßige Software-Versionen, die das Betriebssystem, Binärdateien von Applikationen und Software Updates enthalten.
| Hilft dabei, das StorageGRID System mit aktueller Software und Binärdateien zu aktualisieren. | -- 


| Root-Anmeldung über Secure Shell (SSH) deaktiviert  a| 
Die Root-Anmeldung über SSH ist auf allen StorageGRID Nodes deaktiviert. SSH-Zugriff verwendet Zertifikatauthentifizierung.
| Hilft Kunden, sich vor einem möglichen Remote-Passwort-Cracking der Root-Anmeldung zu schützen. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 


| Automatisierte Zeitsynchronisierung  a| 
StorageGRID synchronisiert Systemuhren jedes Node automatisch mit mehreren externen NTP-Servern (Time Network Time Protocol). Mindestens vier NTP-Server von Stratum 3 oder höher sind erforderlich.
| Stellt die gleiche Zeitreferenz für alle Knoten sicher. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 


| Getrennte Netzwerke für Client-, Admin- und internen Grid-Traffic  a| 
StorageGRID Software Nodes und Hardware Appliances unterstützen mehrere virtuelle und physische Netzwerkschnittstellen, sodass die Kunden den Client-, Administrations- und internen Grid-Traffic über verschiedene Netzwerke trennen können.
| Grid-Administratoren können internen und externen Netzwerkverkehr trennen und Datenverkehr über Netzwerke mit unterschiedlichen SLAs bereitstellen. | -- 


| Mehrere virtuelle LAN-Schnittstellen (VLAN)  a| 
StorageGRID unterstützt die Konfiguration von VLAN-Schnittstellen auf Ihren StorageGRID-Client- und Grid-Netzwerken.
| Grid-Administratoren können den Datenverkehr von Applikationen partitionieren und isolieren, um so Sicherheit, Flexibilität und Performance zu gewährleisten. |  


| Nicht Vertrauenswürdiges Client-Netzwerk  a| 
Die nicht vertrauenswürdige Client-Netzwerkschnittstelle akzeptiert eingehende Verbindungen nur an Ports, die explizit als Load-Balancer-Endpunkte konfiguriert wurden.
| Stellt sicher, dass Schnittstellen geschützt sind, die nicht vertrauenswürdigen Netzwerken zugänglich sind. | -- 


| Konfigurierbare Firewall  a| 
Verwaltung offener und geschlossener Ports für Admin-, Grid- und Client-Netzwerke.
| Ermöglichen Sie Grid-Administratoren, den Zugriff auf Ports zu steuern und den genehmigten Gerätezugriff auf die Ports zu verwalten. |  


| Erweitertes SSH-Verhalten  a| 
Deaktivieren Sie SSH standardmäßig vor der Installation.  Im Standardzustand ist der SSH-Zugriff nur auf die Adresse der Link-Local-Verwaltungsports aktiviert.  Die Passwörter für die Benutzer „Admin“ und „Root“ sind auf die Seriennummer des Compute Controllers des Geräts eingestellt.  Die Anmeldung ist nur auf der seriellen Konsole und der grafischen Konsole (BMC KVM) zulässig.  SSH ist auf allen Netzwerkports deaktiviert.
| Verbessert den Netzwerkzugriffsschutz. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 


| Node-Verschlüsselung  a| 
Als Teil der neuen KMS-Host-Server-Verschlüsselungsfunktion wird dem StorageGRID-Appliance-Installationsprogramm eine neue Einstellung für die Knotenverschlüsselung hinzugefügt.
| Diese Einstellung muss während der Hardwarekonfigurationsphase der Appliance-Installation aktiviert werden. | SEC-Regel 17a-4(f) CTFC 1.31(c)-(d) (FINRA) Regel 4511(c) 
|===