---
permalink: technical-reports/monitor-audit-log-monitoring.html 
sidebar: sidebar 
keywords: audit logs, storagegrid 
summary: Erfahren Sie, wie Sie das StorageGRID-Revisionsprotokoll detaillierte Einblicke in Mandanten- und Grid-Aktivitäten erhalten und wie Sie Tools wie Splunk für Protokollanalysen nutzen können. 
---
= Verwenden Sie Prüfprotokolle, um StorageGRID zu überwachen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie Sie das StorageGRID-Revisionsprotokoll detaillierte Einblicke in Mandanten- und Grid-Aktivitäten erhalten und wie Sie Tools wie Splunk für Protokollanalysen nutzen können.

Mit dem StorageGRID Revisionsprotokoll können Sie detaillierte Informationen über Mandanten und Grid-Aktivitäten erfassen. Das Revisionsprotokoll kann zur Analyse durch NFS offengelegt werden. Ausführliche Anweisungen zum Exportieren des Überwachungsprotokolls finden Sie im Administratorhandbuch.

Nach dem Export der Prüfung können Sie Protokollanalyse-Tools wie Splunk oder Logstash + Elasticsearch verwenden, um die Mandantenaktivität zu verstehen oder detaillierte Rechnungs- und Chargeback-Berichte zu erstellen.

Details zu Audit-Meldungen sind in der StorageGRID-Dokumentation enthalten. Siehe https://docs.netapp.com/us-en/storagegrid-118/audit/audit-messages-main.html["Audit-Meldungen"^].
