---
sidebar: sidebar 
permalink: technical-reports/data-security/index.html 
keywords: security features, storagegrid 
summary: Entdecken Sie die integrierten Sicherheitsfunktionen der StorageGRID Objekt-Storage-Lösung. 
---
= Sichern von StorageGRID-Daten und -Metadaten in einem Objektspeicher
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Entdecken Sie die integrierten Sicherheitsfunktionen der StorageGRID Objekt-Storage-Lösung.

Dies ist ein Überblick über die vielen Sicherheitsfunktionen in NetApp® StorageGRID®, die Datenzugriff, Objekte und Metadaten, administrativen Zugriff und Plattformsicherheit abdecken. Es wurde aktualisiert und enthält nun die neuesten Funktionen, die mit StorageGRID 11.9 veröffentlicht wurden.

Sicherheit ist ein integraler Bestandteil der NetApp StorageGRID Objekt-Storage-Lösung. Die Sicherheit ist besonders wichtig, da viele Arten von umfangreichen Datenmengen, die gut für Objekt-Storage geeignet sind, ebenfalls sehr sensibel sind und gesetzlichen Vorschriften und Compliance unterliegen. Während sich die Funktionen von StorageGRID weiterentwickeln, stellt die Software viele Sicherheitsfunktionen zur Verfügung, die von unschätzbarem Wert sind, um die Sicherheit eines Unternehmens zu schützen und dem Unternehmen dabei zu helfen, die Best Practices der Branche einzuhalten.

Dieses Dokument bietet einen Überblick über die zahlreichen Sicherheitsfunktionen in StorageGRID 11.9, die in fünf Kategorien unterteilt sind:

* Sicherheitsfunktionen für den Datenzugriff
* Sicherheitsfunktionen für Objekte und Metadaten
* Sicherheitsfunktionen für die Administration
* Plattformsicherheitsfunktionen
* Cloud-Integration


Dieses Dokument ist als Sicherheitsdatenblatt gedacht. Es enthält keine Angaben dazu, wie das System so konfiguriert wird, dass es die in aufgeführten Sicherheitsfunktionen unterstützt, die nicht standardmäßig konfiguriert sind. Das https://docs.netapp.com/us-en/storagegrid-118/harden/index.html["Leitfaden zum StorageGRID Hardening"^] ist auf der offiziellen Seite verfügbar https://docs.netapp.com/us-en/storagegrid-118/["StorageGRID-Dokumentation"^] .

Zusätzlich zu den in diesem Bericht beschriebenen Funktionen folgt StorageGRID den https://www.netapp.com/us/legal/vulnerability-response.aspx["NetApp Richtlinie zur Reaktion auf und Benachrichtigung bei Produktsicherheitsschwachstellen"^]. Gemeldete Schwachstellen werden überprüft und entsprechend dem Reaktionsprozess für Produktsicherheitsvorfälle reagiert.

NetApp StorageGRID bietet erweiterte Sicherheitsfunktionen für äußerst anspruchsvolle Enterprise-Objekt-Storage-Anwendungsfälle.



== Wo Sie weitere Informationen finden

Sehen Sie sich die folgenden Dokumente und/oder Websites an, um mehr über die in diesem Dokument beschriebenen Informationen zu erfahren:

* NetApp StorageGRID: Bewertung DER Compliance-Anforderungen gemäß SEC 17a-4(f), FINRA 4511(c) und CFTC 1.31(c)-(d) https://www.netapp.com/media/9041-ar-cohasset-netapp-storagegrid-sec-assessment.pdf[]
* StorageGRID 11.9 Dokumentationsseite https://docs.netapp.com/us-en/storagegrid-119/[]
* NetApp Produktdokumentation https://www.netapp.com/support-and-training/documentation/[]




== Begriffe und Akronyme

Dieser Abschnitt enthält Definitionen für die im Dokument verwendete Terminologie.

[cols="40,60"]
|===
| Begriff oder Akronym | Definition 


| S3 | Simple Storage Service. 


| Client | Eine Applikation, die eine Schnittstelle zu StorageGRID entweder über das S3-Protokoll für den Datenzugriff oder das HTTP-Protokoll für das Management bietet. 


| Mandantenadministrator | Der Administrator des StorageGRID-Mandantenkontos 


| Mandantenbenutzer | Ein Benutzer in einem StorageGRID-Mandantenkonto 


| TLS | Sicherheit In Transportschicht 


| ILM | Information Lifecycle Management 


| LAN | Lokales Netzwerk 


| Grid-Administrator | Der Administrator des StorageGRID-Systems 


| Raster | Dem StorageGRID-System 


| Eimer | Ein Container für in S3 gespeicherte Objekte 


| LDAP | Lightweight Directory Access Protocol 


| SEK. | Securities and Exchange Commission; regelt Börsenmitglieder, Makler oder Händler 


| FINRA | Aufsichtsbehörde für die Finanzindustrie; entspricht den Format- und Medienanforderungen der SEC Rule 17a-4(f) 


| CFTC | Commodities Futures Trading Commissions; regelt den Handel mit Rohstofftermingeschäften 


| NIST | National Institute of Standards and Technology 
|===