---
sidebar: sidebar 
permalink: technical-reports/bare-metal/start-storagegrid-host-service.html 
keywords: host service, storagegrid 
summary: Erfahren Sie, wie Sie den StorageGRID Host Service starten. 
---
= Starten Sie den StorageGRID Host Service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../../media/


[role="lead"]
Erfahren Sie, wie Sie den StorageGRID Host Service starten.

Um die StorageGRID-Nodes zu starten und sicherzustellen, dass sie nach einem Neustart des Hosts neu gestartet werden, müssen Sie den StorageGRID-Hostdienst aktivieren und starten.

Führen Sie zum Starten des StorageGRID Host Service die folgenden Schritte aus.

.Schritte
. Führen Sie auf jedem Host folgende Befehle aus:
+
[listing]
----
sudo systemctl enable storagegrid
sudo systemctl start storagegrid
----
+

NOTE: Der Startvorgang kann bei der ersten Ausführung einige Zeit in Anspruch nehmen.

. Führen Sie den folgenden Befehl aus, um sicherzustellen, dass die Bereitstellung fortgesetzt wird:
+
[listing]
----
sudo storagegrid node status node-name
----
. Führen Sie für jeden Knoten, der den Status oder zurückgibt `Not-Running` `Stopped`, den folgenden Befehl aus:
+
[listing]
----
sudo storagegrid node start node-name
----
+
Beispielsweise würden Sie angesichts der folgenden Ausgabe den Node starten `dc1-adm1` :

+
[listing]
----
[user@host1]# sudo storagegrid node status
Name Config-State Run-State
dc1-adm1 Configured Not-Running
dc1-sn1 Configured Running
----
. Wenn Sie den StorageGRID-Host-Service bereits aktiviert und gestartet haben (oder wenn Sie nicht sicher sind, ob der Service aktiviert und gestartet wurde), führen Sie auch den folgenden Befehl aus:
+
[listing]
----
sudo systemctl reload-or-restart storagegrid
----

